before_script:
  - psql -c 'create database emailsearch_test;' -U postgres
  - RAILS_ENV=test bundle exec rake --trace db:migrate
language: ruby
rvm:
  - 2.0.0
script: "TEST_SOLR=true bundle exec rspec"
notifications:
  email:
    recipients:
      - kigster@gmail.com
    on_success: never
    on_failure: always

