services:
  - postgresql
before_script:
  - psql -c 'create database emailsearch_test;' -U postgres
  - RAILS_ENV=test bundle exec rake --trace db:migrate
cache: bundler
language: ruby
rvm:
  - 2.5.1
script: "bundle exec rspec --format documentation"
notifications:
  email:
    recipients:
      - kigster@gmail.com
    on_success: never
    on_failure: always

