common: &common
  encoding: unicode
  pool: 4
  adapter: postgresql
  username: postgres
  password: 
  host: 127.0.0.1
  port: 5432

development:
  <<: *common
  database: emailsearch_development

test:
  <<: *common
  database: emailsearch_test

production:
  <<: *common
  database: emailsearch_production

